### ISSUE TITLE
サンプルコードとディレクトリの対応表をREADMEに入れたい

### ISSUE THREAD

**Issue by sizuhiko** [kdg-hacks/kdg-hacks-examples#1]
表形式が良いとおもっています。
以下のような感じで

|製品名|ディレクトリ|概要|参考URL|
|---------|------------|-------|----|
| xxxセンサー | [Hello-xxxxx](xxxx) |xxxxの値を取得するセンサー|[公式Wiki](wiki)|
| xxxリモコン| [Hello-xxxxx](xxxx) |xxxを操作するリモコン|[公式サイト](site)|

**Comment by KazuyukiEguchi** [comment]
とりあえず、表を反映させました。
内容は後ほど

**Comment by k1life** [comment]
それなりの形になったのでクローズします！
