### ISSUE TITLE
[m5stack] 各種センサーの動作確認

### ISSUE THREAD

**Issue by oh-yamada** [kdg-hacks/kdg-hacks-examples#28]
- 公式ドキュメントにあるサンプルを動かしてみる
- 特性把握、例えば、精度がよくないとか、計測できないとか。。。
- README作成
- 必要であれば今回用にサンプルを作る

**Comment by LittleWat** [comment]
こちらはプロジェクトを作成しましたのでこちらで管理しようと思います。
https://github.com/kdg-hacks/kdg-hacks-examples/projects/2
