### ISSUE TITLE
httpsで外部WebAPIと連係するサンプルの作成

### ISSUE THREAD

**Issue by k1life** [kdg-hacks/kdg-hacks-examples#5]
Wio LTE M1/NB1で現状直接のhttps通信ができないそうなので、soracom beam/funnel経由で外に抜ける必要があり、この雛形となるサンプルがほしい！

**Comment by KazuyukiEguchi** [comment]
Hello-SORACOM-beam で、SORACOM Beam経由で、IFTTTへ送信する例を作ってみました。
SORACOMの設定方法は、画像で格納してあります。

**Comment by k1life** [comment]
ありがとうございます！クローズします！
